#!/bin/bash
# dxmt-aoe4-pack launcher (installed copy lives in the pack home; setup.sh fills in __DEST__).
# $DEST/Engine and $DEST/Helpers/x87sidecar are the pack's own Wine build and sidecar helper,
# copied there from the pack by setup.sh — nothing outside the pack home is used at runtime.
#
# Settings live in ONE file: $DEST/aoe4.conf (key = value, written by setup.sh, edit and relaunch).
# Command-line flags override it for a single run:
#   aoe4.sh [--pace N] [--plain | --patches off] [--hud off] [--metalfx X] [--pending N] [--print-env] [--plain]
#   --print-env  show the resolved settings/env and the generated dxmt.conf, do not launch.
# Advanced DXMT options go to $DEST/dxmt.extra.conf (appended verbatim to the generated dxmt.conf).
set -u
DEST="__DEST__"
E="$DEST/Engine"
DEPS="$DEST/deps/Frameworks"
CONF="$DEST/aoe4.conf"

# ---- defaults, then aoe4.conf, then flags ----
pace=60; patches=on; hud=on; metalfx=0; pending_presents=2
if [ -f "$CONF" ]; then
  while IFS= read -r line; do
    line="${line%%#*}"; line="${line//[[:space:]]/}"
    [ -z "$line" ] && continue
    k="${line%%=*}"; v="${line#*=}"
    case "$k" in
      pace|patches|hud|metalfx|pending_presents) printf -v "$k" '%s' "$v" ;;
      *) echo "[aoe4-pack] unknown key in aoe4.conf: $k (ignored)" >&2 ;;
    esac
  done < "$CONF"
fi
print_only=0
while [ $# -gt 0 ]; do
  case "$1" in
    --pace) pace="$2"; shift 2 ;;
    --plain) patches=off; shift ;;
    --patches) patches="$2"; shift 2 ;;
    --hud) hud="$2"; shift 2 ;;
    --metalfx) metalfx="$2"; shift 2 ;;
    --pending) pending_presents="$2"; shift 2 ;;
    --print-env) print_only=1; shift ;;
    --) shift; break ;;
    *) break ;;
  esac
done
case "$pace" in ''|*[!0-9]*) echo "[aoe4-pack] pace must be a number (0 = uncapped), got '$pace'" >&2; exit 2 ;; esac

# ---- generated dxmt.conf: fixed part + settings + user extras ----
GEN="$DEST/dxmt.generated.conf"
{
  echo "# generated by aoe4.sh from aoe4.conf — do not edit; put extras in dxmt.extra.conf"
  echo "dxgi.customVendorId = 10de"
  echo "dxgi.customDeviceId = 2484"
  echo "dxgi.customDeviceDesc = NVIDIA GeForce RTX 3070"
  if [ "$pace" != "0" ]; then
    echo "d3d12.preferredMaxFrameRate = $pace"
    echo "d3d12.cpuPacing = True"
  fi
  if [ "$metalfx" != "0" ]; then
    echo "d3d12.metalSpatialUpscaleFactor = $metalfx"
  fi
  [ -f "$DEST/dxmt.extra.conf" ] && { echo "# --- dxmt.extra.conf ---"; cat "$DEST/dxmt.extra.conf"; }
} > "$GEN"

export WINEPREFIX="$DEST/prefix"
# A home installed before the engine renamed the Windows profile still holds
# C:\users\crossover. Letting this engine open it would leave the player's
# settings, saves and screenshots in a profile nothing looks at any more, so
# the rename happens here too, not only during setup. An already-named prefix
# costs one directory test, and a launch while Steam is already up in this
# same prefix (the applaunch below is forwarded to it) is exactly that case.
# The name comes from the engine in this home, never from this script:
# renaming the profile under an engine that still answers "crossover" would
# cause the very loss the rename exists to prevent.
PROFILE_USER="$(tr -d '[:space:]' < "$DEST/Engine/.profile-user" 2>/dev/null || true)"
if [ -x "$DEST/migrate-prefix-user.sh" ]; then
  bash "$DEST/migrate-prefix-user.sh" "$WINEPREFIX" "$PROFILE_USER" || {
    echo "[aoe4-pack] the Windows profile in $WINEPREFIX could not be renamed to $PROFILE_USER; not starting." >&2
    exit 12
  }
fi
export WINELOADER="$E/bin/wine"
export WINESERVER="$E/bin/wineserver"
export WINEDLLPATH="$DEST/dxmt:$E/lib/wine"
export WINEDLLOVERRIDES="winemenubuilder.exe=;mscoree,mshtml=;gameoverlayrenderer,gameoverlayrenderer64=;dxgi,d3d11,d3d12,atidxx64=n,b;nvapi64,nvngx="
export WINEDEBUG=-all
export ROSETTA_ADVERTISE_AVX=1
export WINEMSYNC=1 WINEESYNC=0
export DYLD_LIBRARY_PATH="$DEPS"
export DYLD_FALLBACK_LIBRARY_PATH="$DEPS:/usr/lib"
export AOELAB_STEAM_SINGLEPROCESS=1
export AOELAB_COUNTERS_DIR="$DEST/telemetry/counters"
if [ "$patches" = "on" ]; then
  export AOELAB_SOFTFAULT_GAME=1 AOELAB_CODE_CACHE_GAME=1
  export AOELAB_SIDECAR_PATH="$DEST/Helpers/x87sidecar"
else
  unset AOELAB_SOFTFAULT_GAME AOELAB_CODE_CACHE_GAME AOELAB_SIDECAR_PATH
fi
export DXMT_D3D12_MAX_PENDING_PRESENTS="$pending_presents"
export DXMT_CONFIG_FILE="$GEN"
export DXMT_LOG_LEVEL="${DXMT_LOG_LEVEL:-error}" DXMT_LOG_PATH="$DEST/logs"
export DXMT_FRAME_LOG="$DEST/telemetry/framelog-aoe4"
export DXMT_USE_DEFAULT_METAL_CACHE=1
if [ "$hud" = "on" ]; then export MTL_HUD_ENABLED=1; else export MTL_HUD_ENABLED=0; fi
mkdir -p "$DEST/logs" "$DEST/telemetry/counters"

echo "[aoe4-pack] pace=$pace patches=$patches hud=$hud metalfx=$metalfx pending_presents=$pending_presents (from $CONF + flags)" >&2
if [ "$print_only" = 1 ]; then
  echo "--- $GEN"; cat "$GEN"
  echo "--- env"; env | grep -E '^(WINE|DXMT_|AOELAB_|MTL_HUD|ROSETTA_|DYLD_)' | sort
  exit 0
fi
if pgrep -q -f "$E/bin/wineserver"; then
  : # our own session is already up (Steam running) — the applaunch below is forwarded to it
fi
# In-game V-Sync Off / Limit Unlimited / Fullscreen Desktop: applied once the profile exists.
python3 "$DEST/patch-profile.py" "$WINEPREFIX" --quiet >&2
exec "$E/bin/wine" 'C:\Program Files (x86)\Steam\steam.exe' -applaunch 1466860 "$@"
